### ISSUE TITLE
Error: prevented records from being saved

### ISSUE THREAD

**Issue by DrTrills** [aruizramon/frappe_analytics#1]
Hello,

I deployed this app which ended up breaking the permissions or something. We noticed the issue with HR > Employee where HR Manager was unable to save/create. After removing the app our permissions worked as expected. Would suggest testing this more to ensure you it doesn't accidentally drop a table or corrupt a site.

Thank you

**Comment by aruizramon** [comment]
@DrTrills This actually was fixed today! 

But this is a good reminder to me to make a **big** note in the readme that this is not a stable / production suitable app yet!
